In [1]:
from numpy import *

In [2]:
random.rand(4, 4)

array([[0.27661035, 0.56177801, 0.71055864, 0.06024838],
       [0.85393311, 0.06845377, 0.24599059, 0.60277952],
       [0.15598945, 0.48609348, 0.94777958, 0.0070559 ],
       [0.82976698, 0.47081757, 0.71053011, 0.06195491]])

In [3]:
randMat = mat(random.rand(4, 4))

In [5]:
randMat.I

matrix([[ 0.67892227, -0.59357932, -0.1377519 ,  0.99650564],
        [-0.20675841, -0.43984994,  1.97601789, -1.57542132],
        [ 3.05773984,  0.22094703, -0.60511824, -1.14764612],
        [-2.99307675,  1.39365503, -0.72095969,  1.80954838]])

In [6]:
invRandMat = randMat.I

In [7]:
randMat * invRandMat

matrix([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         -3.46944695e-17],
        [-4.44089210e-16,  1.00000000e+00,  0.00000000e+00,
          1.11022302e-16],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         -2.77555756e-16],
        [ 0.00000000e+00,  0.00000000e+00,  5.55111512e-17,
          1.00000000e+00]])

In [8]:
myEye = randMat * invRandMat
myEye - eye(4)

matrix([[ 2.22044605e-16,  0.00000000e+00,  0.00000000e+00,
         -3.46944695e-17],
        [-4.44089210e-16,  0.00000000e+00,  0.00000000e+00,
          1.11022302e-16],
        [ 0.00000000e+00,  0.00000000e+00,  4.44089210e-16,
         -2.77555756e-16],
        [ 0.00000000e+00,  0.00000000e+00,  5.55111512e-17,
          0.00000000e+00]])